### ISSUE TITLE
Unable to access Magento

### ISSUE THREAD

**Issue by oddietaco** [magenx/Magento-2-aws-cluster-terraform#5]
The `terraform apply` went really well, and it looks like every needed resource was provisioned. I'm now trying to access the Magento storefront, and I notice that there are two ALBs - an inner and an outer. When I point my browser at the DNS entry for the outer ALB, I get the nginx configuration page that just says "Welcome to nginx!"

**Comment by selcuk-cofe** [comment]
@oddietaco that also same for me just applied now.

**Comment by selcuk-cofe** [comment]
Update: after deep dive to System Manager , I saw that SSM couldn't run command on instances for SSM Document runShellScript to install magento. I also saw that ssm document created already should I run manually for build instance machine ?

**Comment by magenx** [comment]
nginx config will be updated soon
also there is some issue with 3rd party magento module.

**Comment by selcuk-cofe** [comment]
Thanks for the update.

**Comment by selcuk-cofe** [comment]
> #[mageplaza/magento-2-smtp#309 (comment)](https://github.com/mageplaza/magento-2-smtp/issues/309#issue-923487376)

is there any temporary workground to do on terraform side ? or where code located on codecommit maybe manually we can edit composer.lock for the module

**Comment by magenx** [comment]
all the git transit operations on your cloudshell,
files synced to codecommit repo, cloned to ec2 instance.

you can edit files before you run magento instalation if you need.

**Comment by selcuk-cofe** [comment]
thanks , which instance I should start installing each of them separately ? or just in build instance ?

**Comment by selcuk-cofe** [comment]
again , I couldn’t be successful after remove smtp module from composer.lock file and re-run ssm document script from system manager.

**Comment by selcuk-cofe** [comment]
any update ? I tried with your latest commit which updated nginx conf still same. After infra created how to install magento with ssm document ? its failed when I run for created instances. I saw your "Nginx welcome" page for outher application load balancer

**Comment by magenx** [comment]
the easiest way for you will be to run ssm installation document on admin instance, (select instance from list)
if document run successfully , then up to date magento files and settings will be pulled to frontend.
then depends on your DNS you need to point domain name to outer load balancer or its ip addresses.
then call your domain name. you will see magento frontend page.

**Comment by selcuk-cofe** [comment]
Hello thank you point me to instance, I successfully run ssm document on admin instance here is ssm output log [https://justpaste.it/8wrhn](url) Still ı can not see magento frontend page , just ı saw Nginx welcome page

**Comment by selcuk-cofe** [comment]
Update: when I run ssm document I figured out document was searching for composer.json file under /home/brandname/public_html/ but there file isn't exist.So I ssh to admin instance with aws cli ssm mananer plugin. Manually created composer.json file under that directory with file values on codecommit repository and run it again.

Here is full log : [https://justpaste.it/3b80j](url) and still no luck load balancer just showing nginx webpage

**Comment by magenx** [comment]
you can debug it - just check if nginx config was applied, 
welcome page = default nginx, no config from user_data.

this is not related to magento installation, because instances already configured, so if you call your domain
you must see either:
502 error / https error - wrong domain
redirect loop to /setup/ - when magento not installed

luma frontpage - magento installed

**Comment by selcuk-cofe** [comment]
> you can debug it - just check if nginx config was applied,
> welcome page = default nginx, no config from user_data.
> 
> this is not related to magento installation, because instances already configured, so if you call your domain
> you must see either:
> 502 error / https error - wrong domain
> redirect loop to /setup/ - when magento not installed
> 
> luma frontpage - magento installed

yes there are no nginx config file under /etc/nginx/sites-enabled with named magento.conf

**Comment by magenx** [comment]
there is only app parameters in variables.tf, nothing else to change for default setup.

**Comment by selcuk-cofe** [comment]
> there is only app parameters in variables.tf, nothing else to change for default setup.

yes , but not working I tried many times.

**Comment by magenx** [comment]
please debug this issue more, check syslog to find any error message, 
we need to understand why configuration failed in your case

**Comment by selcuk-cofe** [comment]
I just apply stack with changing ACM validation method from "EMAIL" to "DNS" and here below my app configuration. there are no any other changes on terraform code side.

`    cidr_block       = "172.30.0.0/16"
    brand            = "cofestore"
    domain           = "cofestore.com"
    admin_email      = "admin@cofestore.com"
    staging_domain   = "stg.cofestore.com"
    source           = "https://github.com/magenx/Magento-2.git"
    language         = "en_US"
    currency         = "EUR"
    timezone         = "UTC"
    php_version      = "7.4"`

**Comment by selcuk-cofe** [comment]
> I just apply stack with changing ACM validation method from "EMAIL" to "DNS" and here below my app configuration. there are no any other changes on terraform code side.
> 
> ` cidr_block = "172.30.0.0/16" brand = "cofestore" domain = "cofestore.com" admin_email = "admin@cofestore.com" staging_domain = "stg.cofestore.com" source = "https://github.com/magenx/Magento-2.git" language = "en_US" currency = "EUR" timezone = "UTC" php_version = "7.4"`

also I can see my acm certificate on my domain with nginx welcome page. so validation method works.

**Comment by selcuk-cofe** [comment]
in admin instances syslog I saw below error.

`main.ERROR: There are no commands defined in the "cron" namespace. #0 /home/cofestore/public_html/vendor/symfony/console/Application.php(657): Symfony\Component\Console\Application->findNamespace() #1 /home/cofestore/public_html/vendor/symfony/console/Application.php(237): Symfony\Component\Console\Application->find() #2 /home/cofestore/public_html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun() #3 /home/cofestore/public_html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun() #4 /home/cofestore/public_html/bin/magento(23): Symfony\Component\Console\Application->run() #5 {main} [] []`

**Comment by selcuk-cofe** [comment]
Update: after deploy stack here is syslog error I have found on frontend instance. can not find nginx.conf.

`Sep  8 10:04:17 ip-172-30-28-58 cloud-init[735]: sed: can't read /etc/nginx/sites-available/magento.conf: No such file or directory
Sep  8 10:04:17 ip-172-30-28-58 cloud-init[735]: sed: can't read /etc/nginx/sites-available/magento.conf: No such file or directory
Sep  8 10:04:17 ip-172-30-28-58 cloud-init[735]: sed: can't read /etc/nginx/conf.d/maps.conf: No such file or directory
Sep  8 10:04:17 ip-172-30-28-58 cloud-init[735]: sed: can't read /etc/nginx/conf.d/maps.conf: No such file or directory`

**Comment by magenx** [comment]
yes, it looks like config not applied, but not sure why exactly,
unless we see specific error message or you share developer access to quickly debug, issue is unknown

**Comment by selcuk-cofe** [comment]
update: also created staging maria db version higher than magento supported version.

**Comment by magenx** [comment]
engine version defined in variables.tf

we just tested full deployment up to product import,
and it looks like everything is working (possible minor issues) but its easy to correct

**Comment by magenx** [comment]
as we didnt get any proper and clear error messages to understand this issue
could be account issue/permissions or custom terraform changes applied
have to close it.

**Comment by youanden** [comment]
@magenx I am running into this issue as well with this repo and this commit fixed the issue. I added a codebuild-breakpoint just before the setup:install and applied this patch directly over the vendor directory.
